// <auto-generated />
using System;
using CuaHangQuanAo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHangQuanAo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Áo Nam"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Quần "
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phụ Kiện"
                        });
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Hàng cao cấp chữ nổi cực nét",
                            ImageUrl = "/images/0609905f-e19d-4626-90b9-19b39fc25169.jpg",
                            Name = "Áo LV xám chữ nổi",
                            Price = 1250000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Phong cách boy phố trẻ trung",
                            ImageUrl = "/images/356b1fa5-1389-4d4c-91bf-47927aad56c8.jpg",
                            Name = "Áo len tay dài boy phố",
                            Price = 450000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Sơ mi họa tiết sang chảnh",
                            ImageUrl = "/images/c8835fcc-32a7-4902-a0a4-99a27087baa5.jpg",
                            Name = "Áo sơ mi Gucci",
                            Price = 950000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Thương hiệu Mikenko chính hãng",
                            ImageUrl = "/images/cf7bc697-39ad-44f7-b9d3-97629d60d46a.jpg",
                            Name = "Áo Mikenko đen hình nổi",
                            Price = 550000m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Phiên bản giới hạn cho fan MU",
                            ImageUrl = "/images/9bab3251-da03-4fd3-973f-ead6791e7973.jpg",
                            Name = "Áo Adidas Man United bản đặc biệt",
                            Price = 850000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Balo Jordan thời trang",
                            ImageUrl = "/images/c17f15fa-5691-4a80-acad-46e77a7e70ac.jpg",
                            Name = "Balo JD Trắng",
                            Price = 650000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Họa tiết monogram kinh điển",
                            ImageUrl = "/images/ed492643-cecc-4871-ab43-c377e059fc40.jpg",
                            Name = "Balo LV Nâu",
                            Price = 1500000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Chất jean co giãn tốt",
                            ImageUrl = "/images/0e66918c-3e38-48e0-a528-01d436e997fe.jpg",
                            Name = "Quần jean đen trơn",
                            Price = 380000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Phong cách bụi bặm",
                            ImageUrl = "/images/f0b1ebd7-133d-4596-868b-ec80974961f6.jpg",
                            Name = "Quần jean rách gối vẩy sơn",
                            Price = 420000m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Dáng suông thoải mái",
                            ImageUrl = "/images/2ae057f9-3f68-4549-bf1a-67945ab121fc.jpg",
                            Name = "Quần ống rộng túi hộp",
                            Price = 350000m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Hoodie Kenzo thêu mặt hổ sắc nét",
                            ImageUrl = "/images/ao6.jpg",
                            Name = "Áo Hoodie Kenzo mặt hổ",
                            Price = 1450000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Họa tiết Cherry đặc trưng của Gucci",
                            ImageUrl = "/images/ao7.jpg",
                            Name = "Áo phông Gucci Cheeryfy",
                            Price = 850000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Dsquared2 Icon đơn giản mà chất",
                            ImageUrl = "/images/ao8.jpg",
                            Name = "Áo phông DSQ ICON trắng",
                            Price = 750000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Louis Vuitton thêu hoa tỉ mỉ",
                            ImageUrl = "/images/ao9.jpg",
                            Name = "Áo phông LV thêu hoa",
                            Price = 1150000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Họa tiết Dog King quyền lực",
                            ImageUrl = "/images/ao10.jpg",
                            Name = "Áo phông Dolce Dog King",
                            Price = 950000m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Balo Dior sang trọng đẳng cấp",
                            ImageUrl = "/images/balo3.jpg",
                            Name = "Balo Christian Dior",
                            Price = 2500000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Balo Gucci họa tiết monogram xám",
                            ImageUrl = "/images/balo4.jpg",
                            Name = "Balo Gucci xám trắng",
                            Price = 1800000m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Quần nỉ bo gấu mặc cực thoải mái",
                            ImageUrl = "/images/quan4.jpg",
                            Name = "Quần dài nỉ Gucci đen",
                            Price = 650000m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Quần đùi thời trang đi biển cực cháy",
                            ImageUrl = "/images/quan5.jpg",
                            Name = "Quần đùi Gucci",
                            Price = 450000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Jean Dsquared2 khóa kéo phong cách",
                            ImageUrl = "/images/quan6.jpg",
                            Name = "Quần jean khóa kéo D2Q",
                            Price = 880000m,
                            StockQuantity = 22
                        });
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Cart", b =>
                {
                    b.HasOne("CuaHangQuanAo.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.CartItem", b =>
                {
                    b.HasOne("CuaHangQuanAo.Data.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangQuanAo.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Order", b =>
                {
                    b.HasOne("CuaHangQuanAo.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("CuaHangQuanAo.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangQuanAo.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Product", b =>
                {
                    b.HasOne("CuaHangQuanAo.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("CuaHangQuanAo.Data.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.User", b =>
                {
                    b.HasOne("CuaHangQuanAo.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("CuaHangQuanAo.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
